# Added because of sendspin cpal dependency:
# libasound2-dev libjack-jackd2-dev libjack-jackd2-0 libdbus-1-dev
# Added because of?: libdbus-1-dev pkg-config musl-tools

# https://github.com/cross-rs/cross/blob/main/docs/config_file.md
[target.armv7-unknown-linux-musleabi]
pre-build = [
    "apt-get update",
    "apt-get install -y libdbus-1-dev pkg-config musl-tools libasound2-dev:armel libjack-jackd2-dev libjack-jackd2-0",
]

[target.arm-unknown-linux-musleabi]
pre-build = [
    "apt-get update",
    "apt-get install -y libdbus-1-dev pkg-config musl-tools libasound2-dev libjack-jackd2-dev libjack-jackd2-0",
]