# UbiHome Light Sensor Example Configuration

ubihome:
  name: 'My Laptop'

# Global light sensor configuration
ambient_light:
  update_interval: 30s

# Individual light sensor
sensor:
  - platform: ambient_light
    name: 'Ambient Light Sensor'
    icon: mdi:brightness-6
    state_class: 'measurement'
    device_class: 'illuminance'
    update_interval: 15s
